"""add_embedding_column_vector_1024

Revision ID: c8e779e98168
Revises: 76551032b7b7
Create Date: 2026-02-18 16:19:54.274609

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e779e98168'
down_revision: Union[str, None] = '76551032b7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('posts', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'embedding')
    # ### end Alembic commands ###
